branches:
  only:
    - master
    - /^\d+.\d+.\d+$/

language: bash
services: docker

env:
  - VARIANT=alpine CONTEXT=. TEST_COMMAND="php -i"
  - VARIANT=fpm-alpine CONTEXT=fpm TEST_COMMAND="php-fpm -i"

before_script:
  - env | sort
  - cd "$CONTEXT"
  - REPOSITORY="digitalbackstage/php"
  - IMAGE="${REPOSITORY}:${VARIANT}"

script:
  - docker build --tag="$IMAGE" .
  - docker run --rm $IMAGE $TEST_COMMAND

after_script:
  - docker images

after_success:
  - if [ "$TRAVIS_BRANCH" == "master" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    docker push $IMAGE;
    fi
  - if [ -n "$TRAVIS_TAG" ]; then
    docker login -e="$DOCKER_EMAIL" -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD";
    TAGGED_IMAGE= "${REPOSITORY}:${TRAVIS_TAG}-${VARIANT}"
    docker tag $IMAGE $TAGGED_IMAGE
    docker push $TAGGED_IMAGE;
    fi
